pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('DOCKERHUB')
    }
    stages {
        stage('Trigged') {
            steps {
                echo "Hello $DOCKERHUB_CREDENTIALS_USR from Slave"
            }
        }
        stage('Login Stage') {
          steps {
            echo "Login : Logging in . . ."
            sh 'docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW'
          }
        }
        stage('Pull from Docker') {
          steps {
               dir('Website') { // change directory to Lab_docker_Jenkins
                    echo "Pull . ."
                    sh "docker-compose pull"
                }
          }
        }
        stage('Website') {
            steps {
                dir('Website') { // change directory to Lab_docker_Jenkins
                    echo "Start . ."
                    sh "docker-compose up -d"
                }
            }
        }
 
}
}